CREATE DATABASE WESTBANKCHILE;

USE WESTBANKCHILE;

CREATE TABLE CUENTA(
	NUMERO_CUENTA INT NOT NULL,
	TIPO_CUENTA VARCHAR(20) NOT NULL, 
	SALDO INT,
    UNIQUE(NUMERO_CUENTA),
    CONSTRAINT PK_CUENTA PRIMARY KEY(NUMERO_CUENTA)
);

CREATE TABLE CLIENTE(
	RUT INT NOT NULL,
    DV VARCHAR(1) NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDO_PATERNO VARCHAR(25) NOT NULL,
    APELLIDO_MATERNO VARCHAR(25),
    DOMICILIO VARCHAR(50) NOT NULL,
    COMUNA VARCHAR(15) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    NUMERO_CUENTA INT NOT NULL,
    UNIQUE(RUT),
    CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT),
    CONSTRAINT FK_CUENTA1 FOREIGN KEY (NUMERO_CUENTA) REFERENCES cuenta(NUMERO_CUENTA)
);

CREATE TABLE HISTORIAL_CLIENTE(
	COD_TRX INT NOT NULL,
    NUMERO_CUENTA INT NOT NULL,
    MONTO INT NOT NULL,
    NUMERO_CUENTA_DES INT NOT NULL,
    FECHA_TRX DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(COD_TRX),
    CONSTRAINT PK_HISTORIAL PRIMARY KEY(COD_TRX),
    CONSTRAINT FK_N_CUENTA FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTA(NUMERO_CUENTA)
);
    
